# Generated by Django 4.0.3 on 2022-10-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('model', models.CharField(choices=[('Lightweigth', '1'), ('Middleweigth', '2'), ('Cruiserweigth', '3'), ('Heavyweigth', '4')], max_length=15)),
                ('weight_limit', models.IntegerField()),
                ('battery_capacity', models.IntegerField()),
                ('state', models.CharField(choices=[('IDLE', '1'), ('LOADING', '2'), ('LOADED', '3'), ('DELIVERING', '4'), ('DELIVERED', '5'), ('RETURNING', '6')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
        ),
    ]
