# Generated by Django 4.0.3 on 2022-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='drone',
        ),
        migrations.AddField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(to='drone.medication'),
        ),
    ]
