# Generated by Django 4.0.3 on 2022-10-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_alter_drone_model_alter_drone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.CharField(choices=[('1', 'Lightweigth'), ('2', 'Middleweigth'), ('3', 'Cruiserweigth'), ('4', 'Heavyweigth')], max_length=1),
        ),
    ]
