# Generated by Django 4.0.3 on 2022-10-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0008_alter_drone_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='state',
        ),
    ]
