# Generated by Django 4.0.3 on 2022-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0009_remove_drone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='weight_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
