# Generated by Django 4.0.3 on 2022-10-07 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0011_drone_created_drone_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('1', 'IDLE'), ('2', 'LOADING'), ('3', 'LOADED'), ('4', 'DELIVERING'), ('5', 'DELIVERED'), ('6', 'RETURNING')], max_length=1, blank=True, null=True),
            preserve_default=False,
        ),
    ]
