# Generated by Django 4.0.3 on 2022-10-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0014_alter_drone_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'verbose_name': 'Drone', 'verbose_name_plural': 'Drones'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
