# Generated by Django 4.0.3 on 2022-10-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0015_alter_drone_options_alter_medication_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='battery_capacity',
            new_name='battery_level',
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('1', 'IDLE'), ('2', 'LOADING'), ('3', 'LOADED'), ('4', 'DELIVERING'), ('5', 'DELIVERED'), ('6', 'RETURNING'), ('6', 'RETURNING')], max_length=1),
        ),
    ]
