# Generated by Django 4.0.3 on 2022-10-09 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0016_rename_battery_capacity_drone_battery_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
                ('battery_level', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('drones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
            options={
                'verbose_name': 'drone_history',
                'verbose_name_plural': 'drones_history',
            },
        ),
    ]
